# Generated by Django 5.2.14 on 2026-07-17 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_unread', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(default='The developer dashboard for engineering teams.', max_length=500)),
                ('location', models.CharField(default='San Francisco, CA', max_length=255)),
                ('website', models.CharField(default='orbitly.io', max_length=255)),
                ('employees', models.CharField(default='12 employees', max_length=100)),
                ('founded', models.CharField(default='Founded 2022', max_length=100)),
                ('industry', models.CharField(default='SaaS / DevTools', max_length=255)),
                ('logo_color', models.CharField(default='#5b5bf7', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('industry', models.CharField(default='SaaS / DevTools', max_length=255)),
                ('location', models.CharField(default='Remote', max_length=255)),
                ('type', models.CharField(default='Part-time', max_length=100)),
                ('duration', models.CharField(default='3 months', max_length=100)),
                ('salary', models.CharField(default='$800/mo', max_length=100)),
                ('tags', models.CharField(default='React, TypeScript, Tailwind', max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='myApp.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('major', models.CharField(default='CS', max_length=255)),
                ('year', models.IntegerField(default=3)),
                ('profile_complete', models.IntegerField(default=98)),
                ('avatar_color', models.CharField(default='#5b5bf7', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Interview', 'Interview'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='myApp.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='myApp.student')),
            ],
        ),
    ]
