# Generated by Django 6.0.1 on 2026-07-24 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='hiring_mode',
            field=models.CharField(choices=[('solo', 'Single student'), ('group_student_led', 'Group – student forms the team'), ('group_startup_led', 'Group – startup picks the team')], default='solo', max_length=30),
        ),
        migrations.AddField(
            model_name='startup',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='open_to',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='startup',
            name='employees',
            field=models.CharField(default='1-10 employees', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='founded',
            field=models.CharField(default='Founded 2023', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='tagline',
            field=models.CharField(default='Building the future.', max_length=500),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.CharField(default='company.com', max_length=255),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('solo', 'Solo project'), ('group_student_led', 'Group – you recruit teammates'), ('group_startup_led', 'Group – startup chose the team')], default='solo', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by_startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='myApp.startup')),
                ('invited_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teammate_invitations', to='myApp.student')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='myApp.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='myApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('invitation', 'Project invitation'), ('invite_accepted', 'Teammate accepted'), ('invite_declined', 'Teammate declined'), ('group_active', 'Group is now active'), ('status_change', 'Application status changed'), ('message', 'New message')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='myApp.invitation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('forming', 'Forming – waiting for all members to accept'), ('active', 'Active – everyone accepted'), ('cancelled', 'Cancelled')], default='forming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='myApp.student')),
                ('members', models.ManyToManyField(blank=True, related_name='project_groups', to='myApp.student')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='myApp.opportunity')),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='myApp.projectgroup'),
        ),
    ]
