# Generated by Django 6.0.7 on 2026-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_studentcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='myApp.opportunity'),
        ),
    ]
